// vue-client/src/sections/login/components/login-container/login-container.component.ts
import Vue from 'vue';
import Component from 'vue-class-component';
import { files, utils } from '../../../../libs';
import { $auth } from '../../../../services';
import { $store } from '../../../../store';

@Component({
	template: files.insert('login', 'login-container'),
})
export class LoginContainer extends Vue {

	public auth = $auth.createSchema();

	public mounted(): void {
		$store.setTitle('Login');
	}

	private clearSchema(): void {
		utils.resetForm('login-container-auth-form');
		$auth.clearSchema(this.auth);
	}

	public login(): void {
		if (!this.auth.user || !this.auth.password) {
			this.clearSchema();
			$store.notify('Empty Fields', 'peru');
		} else {
			const auth = utils.removeTags(this.auth);
			$auth.login(auth).then((isAuth) => {
				if (!isAuth) {
					this.clearSchema();
					$store.notify('Login Failed', 'firebrick');
				} else {
					this.clearSchema();
					$store.notify('Welcome', 'darkslategray');
					utils.delay(() => {
						this.$router.push('/contacts');
					});
				}
			});
		}
	}
}

// angular-client/src/app/sections/login/components/login-container/login-container.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { first } from 'rxjs/operators';
import { Utils } from '../../../../libs';
import { Auth } from '../../../../models';
import { AuthService } from '../../../../services';
import { Store } from '../../../../store';

@Component({
	selector: 'login-container',
	templateUrl: 'login-container.component.html',
	styleUrls: ['login-container.component.scss'],
})
export class LoginContainer implements OnInit {

	@ViewChild('formRef') private formRef: ElementRef<HTMLFormElement>;

	public loginForm = this.authService.buildForm();

	constructor(
		private router: Router,
		private utils: Utils,
		private authService: AuthService,
		private store: Store,
	) {}

	public ngOnInit(): void {
		this.store.setTitle('Login');
	}

	public login(): void {
		if (this.loginForm.invalid) {
			this.store.notify('Empty Fields', 'darkorange');
			this.utils.resetForm(this.formRef.nativeElement);
		} else {
			const auth = this.utils.removeTags<Auth>(this.loginForm.value);
			this.authService.login(auth).pipe(first()).subscribe((isAuth) => {
				if (!isAuth) {
					this.store.notify('Login Failed', 'darkred');
					this.utils.resetForm(this.formRef.nativeElement);
				} else {
					this.store.notify('Welcome', 'darkgreen');
					this.utils.resetForm(this.formRef.nativeElement);
					this.utils.delay(() => {
						this.router.navigateByUrl('contacts');
					});
				}
			});
		}
	}
}
<form
	#formRef
	(submit)="login()"
	[formGroup]="loginForm"
>
	<div class="form-row">
		<input
			type="text"
			placeholder="User"
			formControlName="user"
		>
		<i class="fa fa-user-secret fa-2x"></i>
		<label class="placeholder">User</label>
	</div>
	<div class="form-row form-row-password">
		<input
			type="password"
			placeholder="Password"
			formControlName="password"
		>
		<i class="fa fa-key fa-2x"></i>
		<label class="placeholder">Password</label>
	</div>
	<div class="form-row">
		<button type="submit">
			<i class="fa fa-lock"></i>
			<span>Login</span>
		</button>
	</div>
</form>
