// react-client/src/components/dashboard-contact/dashboard-contact.component.tsx
import * as React from 'react';
import { RouteComponentProps, withRouter } from 'react-router-dom';
import { utils } from '../../libs';
import { Contact } from '../../models';
import { $contact, $notifications } from '../../services';
import './dashboard-contact';

interface SelfProps {
  contact: Contact;
}

type Props = SelfProps & RouteComponentProps;

class InferableComponent extends React.Component<Props> {

  public render(): JSX.Element {
    const { id, name, number } = this.props.contact;
    return (
      <div id="dashboard-contact">
        <div className="table-row-column">{name}</div>
        <div className="table-row-column">{number}</div>
        <div className="button-group">
          <button
            className="edit-button"
            onClick={this.editContact.bind(this, id)}
          >
            <i className="fa fa-pencil-square-o"></i>
            <span>Edit</span>
          </button>
          <button
            className="remove-button"
            onClick={this.removeContact.bind(this, id)}
          >
            <i className="fa fa-times"></i>
            <span>Remove</span>
          </button>
        </div>
      </div>
    );
  }

  private editContact(id: number): void {
    const { path } = this.props.match;
    this.props.history.replace(`${path}/${id}`);
  }

  private removeContact(id: number): void {
    $contact.removeContact(id).then(() => {
      $notifications.push('Removed', 'firebrick');
    });
  }
}

export const DashboardContact = utils.compose(InferableComponent)
  .pipe(withRouter)
  .result();

// angular-client/src/app/components/dashboard-contact/dashboard-contact.component.ts
import { Component, Input } from '@angular/core';
import { first } from 'rxjs/operators';
import { Contact } from '../../models';
import { ContactService } from '../../services';
import { Store } from '../../store';

@Component({
	selector: 'dashboard-contact',
	templateUrl: 'dashboard-contact.component.html',
	styleUrls: ['dashboard-contact.component.scss'],
})
export class DashboardContact {

	@Input() public contact: Contact;

	constructor(
		private $contact: ContactService,
		private store: Store,
	) {}

	public removeContact(id: number): void {
		this.$contact.removeContact(id).pipe(first()).subscribe(() => {
			this.store.notify('Removed', 'darkred');
		});
	}
}
<div class="row-column">{{ contact.name }}</div>
<div class="row-column">{{ contact.number }}</div>
<div class="button-group">
	<button
		type="button"
		class="edit-button"
		[routerLink]="[contact.id]"
	>
		<i class="fa fa-pencil-square-o"></i>
		<span>Edit</span>
	</button>
	<button
		type="button"
		class="remove-button"
		(click)="removeContact(contact.id)"
	>
		<i class="fa fa-times"></i>
		<span>Remove</span>
	</button>
</div>
