// angular-client/src/app/sections/dashboard/components/dashboard-list/dashboard-list.component.ts
import { Component, ElementRef, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { first } from 'rxjs/operators';
import { Utils } from '../../../../libs';
import { Contact, Message } from '../../../../models';
import { ContactService, SocketService } from '../../../../services';
import { Store } from '../../../../store';

@Component({
	selector: 'dashboard-list',
	templateUrl: 'dashboard-list.component.html',
	styleUrls: ['dashboard-list.component.scss'],
})
export class DashboardList implements OnInit, OnDestroy {

	@ViewChild('formRef') private formRef: ElementRef<HTMLFormElement>;

	public query = '';
	public createForm = this.contactService.buildForm();
	public contacts = new Array<Contact>();

	constructor(
		private utils: Utils,
		private contactService: ContactService,
		private socket: SocketService,
		private store: Store,
	) {}

	public ngOnInit(): void {
		this.store.setTitle('Dashboard');
		this.receiveContacts();

		this.socket.client.on(Message.Add, this.receiveContacts.bind(this));
		this.socket.client.on(Message.Save, this.receiveContacts.bind(this));
		this.socket.client.on(Message.Remove, this.receiveContacts.bind(this));
	}

	public ngOnDestroy(): void {
		this.socket.client.off(Message.Add);
		this.socket.client.off(Message.Save);
		this.socket.client.off(Message.Remove);
	}

	private receiveContacts(): void {
		this.contactService.receiveContacts().pipe(first()).subscribe((contacts) => {
			this.contacts = contacts;
		});
	}

	public addContact(): void {
		if (this.createForm.invalid) {
			this.store.notify('Empty Fields', 'darkorange');
			this.utils.resetForm(this.formRef.nativeElement);
		} else {
			const contact = this.utils.removeTags<Contact>(this.createForm.value);
			this.contactService.addContact(contact).pipe(first()).subscribe(() => {
				this.store.notify('Added', 'darkgreen');
				this.utils.resetForm(this.formRef.nativeElement);
			});
		}
	}

	public removeContact(id: number): void {
		this.contactService.removeContact(id).pipe(first()).subscribe(() => {
			this.store.notify('Removed', 'darkred');
		});
	}
}
<div class="search">
	<input
		type="text"
		name="query"
		placeholder="Search"
		[(ngModel)]="query"
	>
	<i class="fa fa-search fa-2x"></i>
	<label class="placeholder">Search</label>
</div>
<form
	#formRef
	class="create-form"
	(submit)="addContact()"
	[formGroup]="createForm"
>
	<div class="form-row">
		<div class="row-column">
			<input
				type="text"
				placeholder="Name"
				formControlName="name"
			>
			<i class="fa fa-user fa-2x"></i>
			<label class="placeholder">Name</label>
		</div>
		<div class="row-column">
			<input
				type="text"
				placeholder="Number"
				formControlName="number"
			>
			<i class="fa fa-phone fa-2x"></i>
			<label class="placeholder">Number</label>
		</div>
	</div>
	<div class="button-group">
		<button type="submit">
			<i class="fa fa-plus"></i>
			<span>Add</span>
		</button>
		<button type="reset">
			<i class="fa fa-paint-brush"></i>
			<span>Clear</span>
		</button>
	</div>
</form>
<div class="table">
	<div
		class="table-row"
		*ngFor="let contact of contacts | search: query"
	>
		<div class="row-column">{{ contact.name }}</div>
		<div class="row-column">{{ contact.number }}</div>
		<div class="button-group">
			<button
				type="button"
				class="edit-button"
				[routerLink]="[contact.id]"
			>
				<i class="fa fa-pencil-square-o"></i>
				<span>Edit</span>
			</button>
			<button
				type="button"
				class="remove-button"
				(click)="removeContact(contact.id)"
			>
				<i class="fa fa-times"></i>
				<span>Remove</span>
			</button>
		</div>
	</div>
</div>

// vue-client/src/sections/dashboard/components/dashboard-list/dashboard-list.component.ts
import Vue from 'vue';
import Component from 'vue-class-component';
import { files, utils } from '../../../../libs';
import { Contact, Message } from '../../../../models';
import { $contact, $socket } from '../../../../services';
import { $store } from '../../../../store';

@Component({
	template: files.insert('dashboard', 'dashboard-list'),
})
export class DashboardList extends Vue {

	public query = '';
	public contact = $contact.createSchema();
	public contacts = new Array<Contact>();
	private registry = new Array<Contact>();
	public search = utils.debounceFactory(this.filterContacts, 320);

	public mounted(): void {
		$store.setTitle('Dashboard');
		this.receiveContacts();

		$socket.client.on(Message.Add, this.receiveContacts.bind(this));
		$socket.client.on(Message.Save, this.receiveContacts.bind(this));
		$socket.client.on(Message.Remove, this.receiveContacts.bind(this));
	}

	public destroyed(): void {
		$socket.client.off(Message.Add);
		$socket.client.off(Message.Save);
		$socket.client.off(Message.Remove);
	}

	public clearSchema(): void {
		utils.resetForm('dashboard-list-create-form');
		$contact.clearSchema(this.contact);
	}

	public filterContacts(): void {
		this.contacts = this.registry.filter((contact) => {
			const pattern = contact.name.toLowerCase();
			const query = this.query.toLowerCase();
			return pattern.includes(query);
		});
	}

	private receiveContacts(): void {
		$contact.receiveContacts().then((contacts) => {
			this.contacts = contacts;
			this.registry = contacts;
		});
	}

	public addContact(): void {
		if (!this.contact.name || !this.contact.number) {
			this.clearSchema();
			$store.notify('Empty Fields', 'peru');
		} else {
			const contact = utils.removeTags(this.contact);
			$contact.addContact(contact).then(() => {
				this.clearSchema();
				$store.notify('Added', 'darkslategray');
			});
		}
	}

	public removeContact(id: number): void {
		$contact.removeContact(id).then(() => {
			$store.notify('Removed', 'firebrick');
		});
	}
}
