// angular-client/src/app/sections/layout/components/layout-header/layout-header.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { first } from 'rxjs/operators';
import { Utils } from '../../../../libs';
import { AuthService } from '../../../../services';
import { Store } from '../../../../store';

@Component({
	selector: 'layout-header',
	templateUrl: 'layout-header.component.html',
	styleUrls: ['layout-header.component.scss'],
})
export class LayoutHeader {

	constructor(
		private router: Router,
		private utils: Utils,
		private authService: AuthService,
		public store: Store,
	) {}

	public logout(): void {
		this.authService.logout().pipe(first()).subscribe(() => {
			this.store.notify('Bye', 'darkgreen');
			this.utils.delay(() => {
				this.router.navigateByUrl('');
			});
		});
	}
}

// vue-client/src/components/layout-header/layout-header.component.ts
import Vue from 'vue';
import Component from 'vue-class-component';
import { files, utils } from '../../libs';
import { Title } from '../../models';
import { $auth } from '../../services';
import { $store } from '../../store';

@Component({
  template: files.insert('layout-header'),
})
export class LayoutHeader extends Vue {

  public get title(): Title {
    return $store.title;
  }

  public get isAuth(): boolean {
    return $store.isAuth;
  }

  public logout(): void {
    $auth.logout().then(() => {
      $store.notify('Bye', 'darkslategray');
      utils.delay(() => {
        this.$router.push('/');
      });
    });
  }
}
