// react-client/src/components/layout-header/layout-header.component.tsx
import * as React from 'react';
import { DispatchProp } from 'react-redux';
import { RouteComponentProps, withRouter } from 'react-router-dom';
import { utils } from '../../libs';
import { $auth, $notifications } from '../../services';
import { SetAuthStatusAction } from '../../store/auth/actions/set-auth-status.action';
import { AuthStatus, AuthTitle } from '../../store/auth/auth.state';
import { adapter } from '../../store/global.reducer';
import './layout-header.style';

interface StateProps {
  status: AuthStatus;
  title: AuthTitle;
}

type Props = StateProps & DispatchProp & RouteComponentProps;

class InferableComponent extends React.Component<Props> {

  public render(): JSX.Element {
    const { title } = this.props;
    return (
      <header id="layout-header">
        <div className="title">
          <i className="fa fa-code"></i>
          <span>{title}</span>
        </div>
        {this.renderElement()}
      </header>
    );
  }

  private renderElement(): JSX.Element {
    const { status } = this.props;
    const isAuth = status === 'authorized';
    return isAuth && (
      <button onClick={this.logout.bind(this)}>
        <i className="fa fa-sign-out"></i>
        <span>Logout</span>
      </button>
    );
  }

  private logout(): void {
    $auth.logout().then(() => {
      $notifications.push('Bye', 'darkslategray');
      utils.delay(() => {
        const action = new SetAuthStatusAction('unauthorized');
        this.props.dispatch(action);
        this.props.history.replace('/');
      });
    });
  }
}

export const LayoutHeader = utils.compose(InferableComponent)
  .pipe(withRouter)
  .pipe(adapter<StateProps>((state) => {
    return {
      status: state.authReducer.status,
      title: state.authReducer.title,
    };
  }))
  .result();

// vue-client/src/components/layout-header/layout-header.component.ts
import Vue from 'vue';
import Component from 'vue-class-component';
import { files, utils } from '../../libs';
import { Color, Text, Title } from '../../models';
import { $auth } from '../../services';
import { ActionKeys } from '../../store/actions/action-keys';

@Component({
  template: files.insert('layout-header'),
})
export class LayoutHeader extends Vue {

  public get title(): Title {
    return this.$store.state.title;
  }

  public get isAuth(): boolean {
    return this.$store.state.isAuth;
  }

  private notify(text: Text, color: Color): void {
    this.$store.dispatch(ActionKeys.Notify, { text, color });
  }

  public logout(): void {
    $auth.logout().then(() => {
      this.notify('Bye', 'darkslategray');
      utils.delay(() => {
        this.$router.push('/');
      });
    });
  }
}
