// vue-client/src/sections/layout/components/layout-header/layout-header.component.ts
import Vue from 'vue';
import Component from 'vue-class-component';
import { files, utils } from '../../../../libs';
import { Text } from '../../../../models';
import { $auth } from '../../../../services';
import { $store } from '../../../../store';

@Component({
	template: files.insert('layout', 'layout-header'),
})
export class LayoutHeader extends Vue {

	public get text(): Text {
		return $store.text;
	}

	public get isAuth(): boolean {
		return $store.isAuth;
	}

	public logout(): void {
		$auth.logout().then(() => {
			$store.notify('Bye', 'darkslategray');
			utils.delay(() => {
				this.$router.push('/');
			});
		});
	}
}

// angular-client/src/app/components/layout-header/layout-header.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { first } from 'rxjs/operators';
import { Utils } from '../../libs';
import { AuthService } from '../../services';
import { Store } from '../../store';

@Component({
	selector: 'layout-header',
	templateUrl: 'layout-header.component.html',
	styleUrls: ['layout-header.component.scss'],
})
export class LayoutHeader {

	constructor(
		private router: Router,
		private utils: Utils,
		private $auth: AuthService,
		public store: Store,
	) {}

	public logout(): void {
		this.$auth.logout().pipe(first()).subscribe(() => {
			this.store.notify('Bye', 'darkgreen');
			this.utils.delay(() => {
				this.router.navigateByUrl('');
			});
		});
	}
}
<header>
	<div
		class="label"
		[style.color]="store.color"
	>
		<i class="fa fa-code"></i>
		<span>{{ store.text }}</span>
	</div>
	<button
		type="button"
		*ngIf="store.isAuth"
		(click)="logout()"
	>
		<i class="fa fa-sign-out"></i>
		<span>Logout</span>
	</button>
</header>
