// angular-client/src/app/components/login-container/login-container.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { first } from 'rxjs/operators';
import { Utils } from '../../libs';
import { Auth } from '../../models';
import { AuthService } from '../../services';
import { Store } from '../../store';

@Component({
  selector: 'login-container',
  templateUrl: 'login-container.component.html',
  styleUrls: ['login-container.component.scss'],
})
export class LoginContainer {

  @ViewChild('formRef') private formRef: ElementRef<HTMLFormElement>;

  public loginForm = this.$auth.buildForm();

  constructor(
    private router: Router,
    private utils: Utils,
    private $auth: AuthService,
    private store: Store,
  ) {}

  public login(): void {
    if (this.loginForm.invalid) {
      this.store.notify('Empty Fields', 'darkorange');
      this.utils.resetForm(this.formRef.nativeElement);
    } else {
      const auth = this.utils.removeTags<Auth>(this.loginForm.value);
      this.$auth.login(auth).pipe(first()).subscribe((isAuth) => {
        if (isAuth) {
          this.store.notify('Welcome', 'darkgreen');
          this.utils.resetForm(this.formRef.nativeElement);
          this.utils.delay(() => {
            this.router.navigateByUrl('contacts');
          });
        } else {
          this.store.notify('Login Failed', 'darkred');
          this.utils.resetForm(this.formRef.nativeElement);
        }
      });
    }
  }
}

<form
  #formRef
  (submit)="login()"
  [formGroup]="loginForm"
>
  <div class="form-row">
    <input
      type="text"
      placeholder="User"
      formControlName="user"
    >
    <i class="fa fa-user-secret fa-2x"></i>
    <label class="placeholder">User</label>
  </div>
  <div class="form-row form-row-password">
    <input
      type="password"
      placeholder="Password"
      formControlName="password"
    >
    <i class="fa fa-key fa-2x"></i>
    <label class="placeholder">Password</label>
  </div>
  <div class="form-row">
    <button type="submit">
      <i class="fa fa-lock"></i>
      <span>Login</span>
    </button>
  </div>
</form>

// vue-client/src/components/login-container/login-container.component.ts
import Vue from 'vue';
import Component from 'vue-class-component';
import { files, utils } from '../../libs';
import { Color, Text } from '../../models';
import { $auth } from '../../services';
import { ActionKeys } from '../../store/actions/action-keys';

@Component({
  template: files.insert('login-container'),
})
export class LoginContainer extends Vue {

  public auth = $auth.createSchema();

  private clearSchema(): void {
    utils.resetForm(this.$refs.formRef as HTMLFormElement);
    $auth.clearSchema(this.auth);
  }

  private notify(text: Text, color: Color): void {
    this.$store.dispatch(ActionKeys.Notify, { text, color });
  }

  public login(): void {
    if (!this.auth.user || !this.auth.password) {
      this.clearSchema();
      this.notify('Empty Fields', 'peru');
    } else {
      const auth = utils.removeTags(this.auth);
      $auth.login(auth).then((isAuth) => {
        if (isAuth) {
          this.clearSchema();
          this.notify('Welcome', 'darkslategray');
          utils.delay(() => {
            this.$router.push('/contacts');
          });
        } else {
          this.clearSchema();
          this.notify('Login Failed', 'firebrick');
        }
      });
    }
  }
}
