// angular-client/src/app/components/dashboard-list/dashboard-list.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { first } from 'rxjs/operators';
import { Contact, Message } from '../../models';
import { ContactService, SocketService } from '../../services';

@Component({
	selector: 'dashboard-list',
	templateUrl: 'dashboard-list.component.html',
	styleUrls: ['dashboard-list.component.scss'],
})
export class DashboardList implements OnInit, OnDestroy {

	public query = '';
	public contacts = new Array<Contact>();

	constructor(
		private $contact: ContactService,
		private socket: SocketService,
	) {}

	public ngOnInit(): void {
		this.receiveContacts();
		this.socket.client.on(Message.Create, this.receiveContacts.bind(this));
		this.socket.client.on(Message.Update, this.receiveContacts.bind(this));
		this.socket.client.on(Message.Remove, this.receiveContacts.bind(this));
	}

	public ngOnDestroy(): void {
		this.socket.client.off(Message.Create);
		this.socket.client.off(Message.Update);
		this.socket.client.off(Message.Remove);
	}

	public trackById(_: number, contact: Contact): number {
		return contact.id;
	}

	private receiveContacts(): void {
		this.$contact.receiveContacts().pipe(first()).subscribe((contacts) => {
			this.contacts = contacts;
		});
	}
}
<div class="search">
	<input
		type="text"
		name="query"
		placeholder="Search"
		[(ngModel)]="query"
	>
	<i class="fa fa-search fa-2x"></i>
	<label class="placeholder">Search</label>
</div>
<dashboard-create></dashboard-create>
<div class="table">
	<dashboard-contact
		*ngFor="let contact of contacts | search: query; trackBy: trackById"
		[contact]="contact"
	></dashboard-contact>
</div>

// vue-client/src/components/dashboard-list/dashboard-list.component.ts
import Vue from 'vue';
import Component from 'vue-class-component';
import { files, utils } from '../../libs';
import { Contact, Message } from '../../models';
import { $contact, $socket } from '../../services';
import { DashboardContact } from '../dashboard-contact/dashboard-contact.component';
import { DashboardCreate } from '../dashboard-create/dashboard-create.component';

@Component({
	template: files.insert('dashboard-list'),
	components: {
		'dashboard-create': DashboardCreate,
		'dashboard-contact': DashboardContact,
	},
})
export class DashboardList extends Vue {

	public query = '';
	public contacts = new Array<Contact>();
	private registry = new Array<Contact>();
	public search = utils.debounceFactory(this.filterContacts, 320);

	public mounted(): void {
		this.receiveContacts();
		$socket.client.on(Message.Create, this.receiveContacts.bind(this));
		$socket.client.on(Message.Update, this.receiveContacts.bind(this));
		$socket.client.on(Message.Remove, this.receiveContacts.bind(this));
	}

	public destroyed(): void {
		$socket.client.off(Message.Create);
		$socket.client.off(Message.Update);
		$socket.client.off(Message.Remove);
	}

	private receiveContacts(): void {
		$contact.receiveContacts().then((contacts) => {
			this.contacts = contacts;
			this.registry = contacts;
		});
	}

	private filterContacts(): void {
		this.contacts = this.registry.filter((contact) => {
			const pattern = contact.name.toLowerCase();
			const query = this.query.toLowerCase();
			return pattern.includes(query);
		});
	}
}
