// angular-client/src/app/components/dashboard-create/dashboard-create.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { first } from 'rxjs/operators';
import { Utils } from '../../libs';
import { Contact } from '../../models';
import { ContactService } from '../../services';
import { Store } from '../../store';

@Component({
  selector: 'dashboard-create',
  templateUrl: 'dashboard-create.component.html',
  styleUrls: ['dashboard-create.component.scss'],
})
export class DashboardCreate {

  @ViewChild('formRef') private formRef: ElementRef<HTMLFormElement>;

  public createForm = this.$contact.buildForm();

  constructor(
    private utils: Utils,
    private $contact: ContactService,
    private store: Store,
  ) {}

  public createContact(): void {
    if (this.createForm.invalid) {
      this.store.notify('Empty Fields', 'darkorange');
      this.utils.resetForm(this.formRef.nativeElement);
    } else {
      const contact = this.utils.removeTags<Contact>(this.createForm.value);
      this.$contact.createContact(contact).pipe(first()).subscribe(() => {
        this.store.notify('Created', 'darkgreen');
        this.utils.resetForm(this.formRef.nativeElement);
      });
    }
  }
}

<form
  #formRef
  (submit)="createContact()"
  [formGroup]="createForm"
>
  <div class="form-row">
    <div class="row-column">
      <input
        type="text"
        placeholder="Name"
        formControlName="name"
      >
      <i class="fa fa-user fa-2x"></i>
      <label class="placeholder">Name</label>
    </div>
    <div class="row-column">
      <input
        type="text"
        placeholder="Number"
        formControlName="number"
      >
      <i class="fa fa-phone fa-2x"></i>
      <label class="placeholder">Number</label>
    </div>
  </div>
  <div class="button-group">
    <button type="submit">
      <i class="fa fa-plus"></i>
      <span>Create</span>
    </button>
    <button type="reset">
      <i class="fa fa-paint-brush"></i>
      <span>Clear</span>
    </button>
  </div>
</form>

// react-client/src/components/dashboard-create/dashboard-create.component.tsx
import * as React from 'react';
import { utils } from '../../libs';
import { Contact } from '../../models';
import { $contact, $notifications } from '../../services';
import './dashboard-create.style';

type State = Contact;

export class DashboardCreate extends React.Component<object, State> {

  private formRef = React.createRef<HTMLFormElement>();

  public state: State = {
    name: '',
    number: '',
  };

  private get isEmpty(): boolean {
    return !this.state.name || !this.state.number;
  }

  public render(): JSX.Element {
    return (
      <section id="dashboard-create">
        <form
          ref={this.formRef}
          onSubmit={this.createContact.bind(this)}
        >
          <div className="form-row">
            <div className="form-row-column">
              <input
                type="text"
                placeholder="Name"
                onInput={this.handleInputChange.bind(this, 'name')}
              ></input>
              <i className="fa fa-user fa-2x"></i>
              <label className="placeholder">Name</label>
            </div>
            <div className="form-row-column">
              <input
                type="text"
                placeholder="Number"
                onInput={this.handleInputChange.bind(this, 'number')}
              ></input>
              <i className="fa fa-phone fa-2x"></i>
              <label className="placeholder">Number</label>
            </div>
          </div>
          <div className="button-group">
            <button type="submit">
              <i className="fa fa-plus"></i>
              <span>Create</span>
            </button>
            <button
              type="button"
              onClick={this.clearSchema.bind(this)}
            >
              <i className="fa fa-paint-brush"></i>
              <span>Clear</span>
            </button>
          </div>
        </form>
      </section>
    );
  }

  private handleInputChange(key: keyof Contact, $event: React.ChangeEvent<HTMLInputElement>): void {
    const { value } = $event.target;
    this.setState({ [key]: value } as object);
  }

  private clearSchema(): void {
    utils.resetForm(this.formRef.current);
    this.setState({
      name: '',
      number: '',
    });
  }

  private createContact($event: React.FormEvent<HTMLFormElement>): void {
    $event.preventDefault();
    if (this.isEmpty) {
      this.clearSchema();
      $notifications.push('Empty Fields', 'peru');
    } else {
      const contact = utils.removeTags(this.state);
      $contact.createContact(contact).then(() => {
        this.clearSchema();
        $notifications.push('Created', 'darkslategray');
      });
    }
  }
}
